name: Generate Clients

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - "proto/**"
      - "src/common/gen/**"

jobs:
  test:
    runs-on: ubuntu-latest

    # Trigger only if the PR is opened or synchronized by T-0 CI APP (sync proto files)
    if: ${{github.event.pull_request.user.login == 't-0-ci[bot]'}}

    steps:
      - name: Generate GitHub APP Token
        uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.CI_APP_ID }}
          private-key: ${{ secrets.CI_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: provider-sdk-ts

      - name: Checkout
        uses: actions/checkout@v4
        with:
          show-progress: false
          token: ${{ steps.app-token.outputs.token }}
          ref: ${{ github.head_ref }}

      - name: Generate Clients
        run: |
          npm i
          npm install -g @bufbuild/buf
          npm run buf:generate

      - name: Commit generated files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto-generate GRPC clients"
          file_pattern: "src/common/gen/**"
